name: "Dance Performance"
description: "All dance motions from the LAFAN1 dataset for expressive movement and coordination training."
motions:
  # All dance motions (8 total)
  - "16726/csv_to_npz/dance1_subject1:latest"
  - "16726/csv_to_npz/dance1_subject2:latest"
  - "16726/csv_to_npz/dance1_subject3:latest"
  - "16726/csv_to_npz/dance2_subject1:latest"
  - "16726/csv_to_npz/dance2_subject2:latest"
  - "16726/csv_to_npz/dance2_subject3:latest"
  - "16726/csv_to_npz/dance2_subject4:latest"
  - "16726/csv_to_npz/dance2_subject5:latest"