name: "Basic Locomotion"
description: "A small set of basic walking motions for quick validation and testing."
motions:
  - "16726/csv_to_npz/walk1_subject1:latest"
  - "16726/csv_to_npz/dance1_subject1:latest"