name: "LAFAN1 Complete Dataset"
description: "Complete LAFAN1 dataset with all 40 motions across 6 categories for comprehensive multi-motion training experiments."
motions:
  # Dance motions (8 total)
  - "16726/csv_to_npz/dance1_subject1:latest"
  - "16726/csv_to_npz/dance1_subject2:latest"
  - "16726/csv_to_npz/dance1_subject3:latest"
  - "16726/csv_to_npz/dance2_subject1:latest"
  - "16726/csv_to_npz/dance2_subject2:latest"
  - "16726/csv_to_npz/dance2_subject3:latest"
  - "16726/csv_to_npz/dance2_subject4:latest"
  - "16726/csv_to_npz/dance2_subject5:latest"
  
  # Walking motions (12 total)
  - "16726/csv_to_npz/walk1_subject1:latest"
  - "16726/csv_to_npz/walk1_subject2:latest"
  - "16726/csv_to_npz/walk1_subject5:latest"
  - "16726/csv_to_npz/walk2_subject1:latest"
  - "16726/csv_to_npz/walk2_subject3:latest"
  - "16726/csv_to_npz/walk2_subject4:latest"
  - "16726/csv_to_npz/walk3_subject1:latest"
  - "16726/csv_to_npz/walk3_subject2:latest"
  - "16726/csv_to_npz/walk3_subject3:latest"
  - "16726/csv_to_npz/walk3_subject4:latest"
  - "16726/csv_to_npz/walk3_subject5:latest"
  - "16726/csv_to_npz/walk4_subject1:latest"
  
  # Running motions (4 total)
  - "16726/csv_to_npz/run1_subject2:latest"
  - "16726/csv_to_npz/run1_subject5:latest"
  - "16726/csv_to_npz/run2_subject1:latest"
  - "16726/csv_to_npz/run2_subject4:latest"
  
  # Sprint motions (2 total)
  - "16726/csv_to_npz/sprint1_subject2:latest"
  - "16726/csv_to_npz/sprint1_subject4:latest"
  
  # Fight and sports motions (5 total)
  - "16726/csv_to_npz/fight1_subject2:latest"
  - "16726/csv_to_npz/fight1_subject3:latest"
  - "16726/csv_to_npz/fight1_subject5:latest"
  - "16726/csv_to_npz/fightAndSports1_subject1:latest"
  - "16726/csv_to_npz/fightAndSports1_subject4:latest"
  
  # Jump motions (3 total)
  - "16726/csv_to_npz/jumps1_subject1:latest"
  - "16726/csv_to_npz/jumps1_subject2:latest"
  - "16726/csv_to_npz/jumps1_subject5:latest"
  
  # Fall and get up motions (6 total)
  - "16726/csv_to_npz/fallAndGetUp1_subject1:latest"
  - "16726/csv_to_npz/fallAndGetUp1_subject4:latest"
  - "16726/csv_to_npz/fallAndGetUp1_subject5:latest"
  - "16726/csv_to_npz/fallAndGetUp2_subject2:latest"
  - "16726/csv_to_npz/fallAndGetUp2_subject3:latest"
  - "16726/csv_to_npz/fallAndGetUp3_subject1:latest"