# Base configuration for BeyondMimic Stage 2 diffusion model training

# Model configuration
model:
  state_dim: 165
  action_dim: 69
  hidden_dim: 512
  num_layers: 6
  num_heads: 8
  history_length: 4
  future_length_states: 32
  future_length_actions: 16
  num_timesteps: 100
  state_schedule_type: cosine
  action_schedule_type: linear
  dropout: 0.1

# Training configuration
training:
  batch_size: 256
  learning_rate: 1.0e-4
  num_epochs: 1000
  warmup_steps: 1000
  gradient_clip: 1.0
  ema_decay: 0.9999
  
  # Optimizer
  optimizer_type: adamw
  weight_decay: 0.01
  betas: [0.9, 0.999]
  
  # Learning rate scheduler
  scheduler_type: warmup_cosine
  min_lr: 1.0e-6
  
  # Loss weights
  state_loss_weight: 1.0
  action_loss_weight: 1.0

# Data configuration
data:
  num_workers: 4
  val_split: 0.1
  augment_noise: true
  noise_scale: 0.01
  action_delay_prob: 0.5
  action_delay_range: [0, 100]

# Logging configuration
logging:
  use_wandb: true
  wandb_project: beyondmimic-stage2
  log_interval: 100
  log_gradient_norm: true
  log_learning_rate: true
  log_samples: true
  sample_interval: 5000
  num_samples: 4

# Checkpoint configuration
checkpoint:
  checkpoint_dir: ./checkpoints
  save_interval: 5000
  save_best: true
  save_last: true
  keep_last_n: 5

# Validation configuration
validation:
  val_interval: 1000
  early_stopping: false
  early_stopping_patience: 10
  early_stopping_min_delta: 1.0e-4

# Device configuration
device: cuda
seed: 42
mixed_precision: false
compile_model: false