# Configuration for joystick velocity control task

# Guidance parameters
guidance_scale: 1.0
gradient_clipping: 10.0
warmup_steps: 5
cooldown_steps: 3

# Rolling inference parameters
horizon: 16
replan_frequency: 1
warm_start_steps: 8
temporal_smoothing: 0.9

# Task configuration
tasks:
  - type: joystick
    velocity: [1.0, 0.0]  # Forward velocity (m/s)
    velocity_weight: 1.0
    acceleration_penalty: 0.1
    weight: 1.0